from aconsys.views.login.window import LoginWindow

items = [
    {
        "codigo": "NIU",
        "descripcion": "ARRIENDO MÍNIMO",
        "cantidad": 1,
        "unidad": "NIU",
        "precio_unitario": "13333.12",
        "valor_venta": "13333.12",
        "igv_linea": "2399.96",
        "total_linea": "15733.08",
        "local_contrato": None,
        "mes_servicio": "12-2025",
        "pago_adelantado": False,
        "tipo_gasto": "ALQUILER_MINIMO",
        "glosa": "PRV GCM 12-2025 3144 BODEGA - BG-3020 TM (3002822)",
        "cc_number": "3120",
        "account_number": "9539119",
    },
    {
        "codigo": "NIU",
        "descripcion": "ARRIENDO MÍNIMO",
        "cantidad": 1,
        "unidad": "NIU",
        "precio_unitario": "13333.12",
        "valor_venta": "13333.12",
        "igv_linea": 2399.96,
        "total_linea": 15733.08,
        "local_contrato": None,
        "mes_servicio": "01-2026",
        "pago_adelantado": False,
        "tipo_gasto": "ALQUILER_MINIMO",
        "glosa": "PRV MIN 01-2026 3120",
        "cc_number": "3120",
        "account_number": "1831101",
    },
    {
        "codigo": "NIU",
        "descripcion": "FONDO PROMOCIÓN",
        "cantidad": 1,
        "unidad": "NIU",
        "precio_unitario": "1155.09",
        "valor_venta": 1155.09,
        "igv_linea": 207.92,
        "total_linea": 1363.01,
        "local_contrato": None,
        "mes_servicio": "01-2026",
        "pago_adelantado": False,
        "tipo_gasto": "FONDO_PROMOCION",
        "glosa": "PRV MIN 01-2026 3120",
        "cc_number": "3120",
        "account_number": "1831101",
    },
    {
        "codigo": "NIU",
        "descripcion": "CONTRIBUCIONES",
        "cantidad": 1,
        "unidad": "NIU",
        "precio_unitario": "1041.94",
        "valor_venta": 1041.94,
        "igv_linea": 187.55,
        "total_linea": 1229.49,
        "local_contrato": None,
        "mes_servicio": "12-2025",
        "pago_adelantado": False,
        "tipo_gasto": "CONTRIBUCIONES",
        "glosa": "PRV MIN 12-2025 3120",
        "cc_number": "3120",
        "account_number": "9539119",
    },
    {
        "codigo": "NIU",
        "descripcion": "RECUPERO DE GASTOS COMUNES",
        "cantidad": 1,
        "unidad": "NIU",
        "precio_unitario": "3612.85",
        "valor_venta": 3612.85,
        "igv_linea": 650.31,
        "total_linea": 4263.16,
        "local_contrato": None,
        "mes_servicio": "12-2025",
        "pago_adelantado": False,
        "tipo_gasto": "GASTOS_COMUNES",
        "glosa": "PRV GCM 12-2025 3144 BODEGA - BG-3020 TM (3002822)",
        "cc_number": "3120",
        "account_number": "9539119",
    },
    {
        "codigo": "NIU",
        "descripcion": "COMISIÓN DE ADMINISTRACIÓN",
        "cantidad": 1,
        "unidad": "NIU",
        "precio_unitario": "180.64",
        "valor_venta": 180.64,
        "igv_linea": 32.52,
        "total_linea": 213.16,
        "local_contrato": None,
        "mes_servicio": "12-2025",
        "pago_adelantado": False,
        "tipo_gasto": "COMISION_ADM",
        "glosa": "PRV MIN 12-2025 3120",
        "cc_number": "3120",
        "account_number": "9539119",
    },
    {
        "codigo": "NIU",
        "descripcion": "COMISIÓN DE ADMINISTRACIÓN",
        "cantidad": 1,
        "unidad": "NIU",
        "precio_unitario": "52.10",
        "valor_venta": 52.1,
        "igv_linea": 9.38,
        "total_linea": 61.48,
        "local_contrato": None,
        "mes_servicio": "12-2025",
        "pago_adelantado": False,
        "tipo_gasto": "COMISION_ADM",
        "glosa": "PRV MIN 12-2025 3120",
        "cc_number": "3120",
        "account_number": "9539119",
    },
    {
        "codigo": "NIU",
        "descripcion": "INGRESOS SERVICIOS COMERCIALES",
        "cantidad": 1,
        "unidad": "NIU",
        "precio_unitario": "1249.39",
        "valor_venta": 1249.39,
        "igv_linea": 224.89,
        "total_linea": 1474.28,
        "local_contrato": None,
        "mes_servicio": "01-2026",
        "pago_adelantado": False,
        "tipo_gasto": "ENERGIA_ELECTRICA",
        "glosa": "PRV MIN 01-2026 3120",
        "cc_number": "3120",
        "account_number": "1831101",
    },
    {
        "codigo": "NIU",
        "descripcion": "INGRESOS SERVICIOS COMERCIALES",
        "cantidad": 1,
        "unidad": "NIU",
        "precio_unitario": "43.71",
        "valor_venta": 43.71,
        "igv_linea": 7.87,
        "total_linea": 51.58,
        "local_contrato": None,
        "mes_servicio": "12-2025",
        "pago_adelantado": False,
        "tipo_gasto": "ENERGIA_ELECTRICA",
        "glosa": "PRV MIN 12-2025 3120",
        "cc_number": "3120",
        "account_number": "9539119",
    },
]


def test_alquileres(executable_file, username, password) -> None:
    login_window = LoginWindow(executable_file)
    main_window = login_window.login(username, password)
    main_window.change_work_period("12")

    success = main_window.register_alquileres_one_by_one(
        receipt_number="11",
        supplier_number="20547530552",
        currency_type="01",
        receipt_type="01",
        issue_date="11/12/2025",
        concept=items[0]["glosa"],
        serie="F001",
        receipt_number_from_invoice="40356",
        items=items,
        has_detraction=True,
        type_detraction="003",
        payment_date="3/01/2024",
        constancia_number="12345678",
        aconsys_date="01/12/2025",
    )

    print(success)
